### ISSUE TITLE
Xmas commission

### ISSUE THREAD

**Issue by Irostovsky** [Arsa-py/test-code-task#1]
Hi @Arsa-py 
I m Ivan from GuestReady.
Thanks for the doing the task.
Just a question, imagine that marketing team decided to set the commission in Dec to 12% and in Jan to 13% because of Xmas.
How the code should be changed?

**Comment by Arsa-py** [comment]
Hello @Irostovsky,

I would change this code by inserting two more variables into the function and adding two elif conditions within the try-except block.

For example:

```
def get_commission(date_str):
    ...
    xmas_season_dec = 12
    xmas_season_jan = 1
    
    try:
        ...
        elif mnth is xmas_season_dec:
            print(f'The GuestReady commission for {date_obj} is 12%')
            return 0.12
        elif mnth is xmas_season_jan:
            print(f'The GuestReady commission for {date_obj} is 13%')
            return 0.13
        ...
```

**Comment by Arsa-py** [comment]
I have updated the code, the Xmas commission has been added.

**Comment by Irostovsky** [comment]
Thanks @Arsa-py  for the update.
Unfortunately we can’t go forward with proposed solution.
The expected one would be:
Define a dict with month_number: commission. Ie 
{1: 0.12,
2: 0.1,
….
}
then just get the commission from dict by month of the passed date.
The solution fixes 2 major issues: there is no need to change a function code when the commission is changed for some particular month.
And preventing magic numbers anti-pattern in code. So data and logic are splitted.

**Comment by Arsa-py** [comment]
Now it is clear to me, thanks for the advice. 
That was actually my initial idea (the dictionary) for solving the task. 
Unfortunately, I didn't apply it. I decided to play around with user input...
Well, do I need to provide you with a new solution?
